algoritmo "Nome do Programa"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   :  Um algpritmo que lê dois numeros e mostra a soma entre eles
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : DATA_ATUAL/MES_ATUAL/ANO_ATUAL
var

    n1, n2, soma: real

inicio

escreva("Digite um numero: ")
leia(n1)
escreva("Digite outro numero: ")
leia(n2)

soma <- n1 + n2

escreval("O resultado de ", n1, " + ", n2, " é igual a " ,soma)
fimalgoritmo