algoritmo "Nome do Programa"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : Uma função que lê o nome da pessoa e dá boas vindas a ela.
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : DATA_ATUAL/MES_ATUAL/ANO_ATUAL
var
    nome: caractere

inicio

    escreva("Qual o seu nome? ")
    leia(nome)
    escreval("Olá, ", nome, " Seja bem vindo!" )
fimalgoritmo