algoritmo "Nome do Programa"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : DATA_ATUAL/MES_ATUAL/ANO_ATUAL
var

    nome: caractere
    salario: real

inicio

    escreva("Digite seu nome: ")
    leia(nome)
    escreval("Digite seu salário: ")
    leia(salario)

    escreval( nome, " recebeu ", salario, " este mês")
fimalgoritmo